### ISSUE TITLE
Empty Outputfile

### ISSUE THREAD

**Issue by berzentine** [mfaruqui/morph-trans#1]
I am trying to use the models on a turkish dataset, but the runs produce 0% accuracy and an empty output file (no change even after changing parameters). The program terminates although, with no errors at all. Possible difference between the same dataset you have provided and I am using is 
1. Size is 1800 : 19000. (10 times bigger dataset you have got. )
2.  ADJ;PSS2S;ABL;SG ADJ;PSS3P;SG ADJ;PSS1P;ACC;PL ADJ;PRS;1;SG;{IPFV/PFV} ADJ;PSS2S;ESS;PL ADJ;PSS2S;PL ADJ;PSS3S;ABL;SG ADJ;PSS1S;NOM;PL ADJ;PSS2P;ACC;PL ADJ;PSS1P;ESS;PL ADJ;PSS1P;ESS;SG kind of file in morph_vocab.txt

Any help would be really nice.

**Comment by mfaruqui** [comment]
Can you email me the exact commands (for training and test) that you are running along with the input files? I am in a conference and might need some days to respond, unless the errors are obvious.
