### ISSUE TITLE
Simple typo in Makefile

### ISSUE THREAD

**Issue by manexagirrezabal** [mfaruqui/morph-trans#3]
I think there is a simple typo in the main Makefile. In the 7th line this can be read:

```INCS=-I$(CNN_DIR) -I$(CNN_BUILD_DIR) -I$(EIGEN)```

and it should be:

```INCS=-I$(CNN_DIR) -I$(CNN_BUILD_DIR) -I$(EIGEN_DIR)```

Thanks!

**Comment by mfaruqui** [comment]
Thanks for pointing this out, I have fixed this, but this should not be making any effect in the compilation.
